module.exports = Object.freeze({
  SUCCESS: 'Success',
  STATUS_CODE_SUCCESS: 200,
  BAD_REQUEST: 'Bad Request',
  STATUS_CODE_BAD_REQUEST: 400,
  MESSAGE_BAD_REQUEST: 'Bad Request, Please check the payload',
  CUSTOM_RESPONSE: 'Custom Response',
  STATUS_CODE_INVALID_SUCCESS: 201,
  STATUS_CODE_UNAUTHORISED: 401,
  LOGIN_SUCCESS: 'Login Successful',
  INVALID_DETAILS: 'Invalid Details, Please check the details',
  INVALID_PASSWORD: 'Invalid Password',
  INVALID_EMAIL: 'Invalid Email, Please check',
  USER_NOT_FOUND: 'User not found',
  STATUS_CODE_INTERNAL_SERVER_ERROR: 500,
  REFRESH_TOKEN_INVALID: 'Invalid Refresh Token',
  REFRESH_TOKEN_EXPIRED: 'Session Expired, Please login',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
});